name: 'Upload to Dropbox'
description: 'Upload files to Dropbox'
author: 'Akshay Dhalwala (forked from Deka)'
branding:
  icon: upload-cloud
  color: blue
inputs:
  dropbox_refresh_token:
    required: true
    description: 'Dropbox refresh token - obtain by following https://www.dropbox.com/oauth2/authorize?client_id=<APP_KEY>&token_access_type=offline&response_type=code and then issuing a POST requestvia curl or postman to https://www.dropbox.com/oauth2/token with the code'
  dropbox_client_id:
    required: true
    description: 'Dropbox app key - https://www.dropbox.com/developers/apps'
  dropbox_client_secret:
    required: true
    description: 'Dropbox app secret - https://www.dropbox.com/developers/apps'
  use_root_namespace:
    required: false
    default: 'false'
    description: 'Use root namespace when working with Dropbox Teams. default: false'
  src:
    required: true
    description: "File to upload to Dropbox. e.g. 'file.txt', '**/*.txt'"
  dest:
    required: false
    default: '/'
    description: "Destination path for upload. e.g. '/file.txt', '/dest/'"
  shared_link:
    required: false
    default: 'false'
    description: 'Create a shared link for the uploaded file - default visibility is public. default: false'
  multiple:
    required: false
    default: 'false'
    description: 'Upload multiple files by glob. default: false'
  mode:
    required: false
    default: 'add'
    description: 'What to do if the file already exists [add, overwrite]. default: add'
  autorename:
    required: false
    default: 'false'
    description: "If there's a conflict, as determined by mode, have the Dropbox server try to autorename the file to avoid conflict. default: false"
  mute:
    required: false
    default: 'false'
    description: "If true, this tells the clients that this modification shouldn't result in a user notification. default: false"
outputs:
  shared_link:
    description: 'Shared link for the uploaded file (empty if shared_link is false)'
runs:
  using: 'node20'
  main: 'dist/index.js'
